### ISSUE TITLE
Concurrent Modification Exception in Checkers

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#147]
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Sent {"msg_type":"gaze","msg_body":{"vertical":"-0.5","horizontal":"-1.0"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"checkers.agent_move","msg_body":{"moveDesc":"5,0//4,1"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"speech","msg_body":{"text":""}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":""}}
Sent {"msg_type":"gaze","msg_body":{"vertical":"0.0","horizontal":"0.0"}}
Sent {"msg_type":"speech","msg_body":{"text":" Nobody beats me "}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":" Nobody beats me "}}
Sent {"msg_type":"checkers.playability","msg_body":{"value":"true"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"gaze","msg_body":{"vertical":"-0.5","horizontal":"-1.0"}}
Received {"msg_type":"checkers.human_played_move","msg_body":{"humanMove":"3,2//5,0"}}
Sent {"msg_type":"checkers.confirm_human_move","msg_body":{"human_move":"confirmed"}}
Sent {"msg_type":"check-- 1 more
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"speech","msg_body":{"text":""}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":""}}
Sent {"msg_type":"gaze","msg_body":{"vertical":"0.0","horizontal":"0.0"}}
Sent {"msg_type":"speech","msg_body":{"text":" How dare you to hit me? "}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":" How dare you to hit me? "}}
Sent {"msg_type":"checkers.playability","msg_body":{"value":"false"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"gaze","msg_body":{"vertical":"0.5","horizontal":"0.5"}}
Sent {"msg_type":"gaze"-- 1 more
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"checkers.agent_move","msg_body":{"moveDesc":"7,2//6,1"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"speech","msg_body":{"text":""}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":""}}
Sent {"msg_type":"gaze","msg_body":{"vertical":"0.0","horizontal":"0.0"}}
Sent {"msg_type":"speech","msg_body":{"text":" Humans are somewhat intelligent but robots are genius "}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":" Humans are somewhat intelligent but robots are genius "}}
Sent {"msg_type":"checkers.playability","msg_body":{"value":"true"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"gaze","msg_body":{"vertical":"-0.5","horizontal":"-1.0"}}
Received {"msg_type":"checkers.human_played_move","msg_body":{"humanMove":"5,0//7,2"}}
Sent {"msg_type":"checkers.confirm_human_move","msg_body":{"human_move":"confirmed"}}
Disposing of edu.wpi.always.checkers.CheckersSchema@7a3afc13...
Exception in thread "edu.wpi.always.checkers.CheckersSchema" java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at edu.wpi.sgf.comment.CommentLibraryHandler.prioritizeByTags(CommentLibraryHandler.java:278)
    at edu.wpi.sgf.comment.CommentingManager.getAgentCommentForHumanMove(CommentingManager.java:148)
    at edu.wpi.always.checkers.CheckersClient.prepareAgentCommentForAMoveBy(CheckersClient.java:241)
    at edu.wpi.always.checkers.StartGamingSequence$CreateCommentsAfterLimbo.enter(StartGamingSequence.java:195)
    at edu.wpi.disco.rt.menu.MenuTurnStateMachine.setState(MenuTurnStateMachine.java:175)
    at edu.wpi.disco.rt.menu.MenuTurnStateMachine.build(MenuTurnStateMachine.java:57)
    at edu.wpi.disco.rt.schema.SchemaBase.propose(SchemaBase.java:104)
    at edu.wpi.always.cm.schemas.ActivityStateMachineSchema.run(ActivityStateMachineSchema.java:25)
    at edu.wpi.always.checkers.CheckersSchema.run(CheckersSchema.java:27)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at edu.wpi.disco.rt.util.ThreadPools$ScheduledFutureTask.run(ThreadPools.java:159)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by mbehrooz** [comment]
Should be resolved.
