### ISSUE TITLE
another bug--occurs during load of Always-Companion

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#219]
No console file. See below:
Agent type = Unity
User ontology file: ......\user\User.owl
Loading user model from: ......\user\User.owl
User name: Diane Ferguson
Using closeness = Companion
Starting DiscoRT...
Starting Collaboration Manager...
Loaded plugin: edu.wpi.always.story.StoryPlugin@2845836a
Loaded plugin: plugins.ExercisePlugin@451e7804
Loaded plugin: plugins.AnecdotesPlugin@43350e24
Loaded plugin: plugins.HealthPlugin@1cc3f207
Loaded plugin: edu.wpi.always.ttt.TTTPlugin@73057e2d
Loaded plugin: edu.wpi.always.srummy.SrummyPlugin@52d1ce4c
Loaded plugin: edu.wpi.always.about.AboutPlugin@25591d82
Loaded plugin: edu.wpi.always.calendar.CalendarPlugin@71679f5c
Loaded plugin: edu.neu.always.skype.SkypePlugin@6475b7d
Loading Greetings.owl
Loaded plugin: edu.wpi.always.greetings.GreetingsPlugin@4fb8896f
Cannot find weather data for 01_23_2014
Using testing data...
Loading Weather.owl
Loaded plugin: edu.wpi.always.weather.WeatherPlugin@7e89481a
Loading Explain.owl
Loaded plugin: edu.wpi.always.explain.ExplainPlugin@95e7f59
Loaded plugin: edu.wpi.always.enroll.EnrollPlugin@1c861995
Loaded plugin: plugins.NutritionPlugin@518e0750
Loaded plugin: edu.wpi.always.checkers.CheckersPlugin@7f8ecd21
Exception in thread "main" org.semanticweb.owlapi.reasoner.InconsistentOntologyException: Inconsistent ontology
    at com.clarkparsia.pellet.owlapiv3.PelletReasoner.convert(PelletReasoner.java:360)
    at com.clarkparsia.pellet.owlapiv3.PelletReasoner.getDataPropertyValues(PelletReasoner.java:438)
    at edu.wpi.always.user.owl.OntologyIndividual.getDataPropertyValues(OntologyIndividual.java:64)
    at edu.wpi.always.user.owl.OntologyIndividual.getDataPropertyValue(OntologyIndividual.java:72)
    at edu.wpi.always.user.owl.OntologyIndividual.getDataPropertyValue(OntologyIndividual.java:68)
    at edu.wpi.always.user.owl.OntologyUserModel.getProperty(OntologyUserModel.java:67)
    at edu.wpi.always.user.UserModelBase.getCloseness(UserModelBase.java:44)
    at edu.wpi.always.RelationshipManager.getSession(RelationshipManager.java:23)
    at edu.wpi.always.cm.schemas.SessionSchema.<init>(SessionSchema.java:42)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:147)
    at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:348)
    at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:272)
    at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:370)
    at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
    at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:692)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:671)
    at edu.wpi.disco.rt.schema.SchemaManager$ConfigSchemaFactory.create(SchemaManager.java:96)
    at edu.wpi.disco.rt.schema.SchemaManager.start(SchemaManager.java:37)
    at edu.wpi.disco.rt.schema.SchemaManager.startUp(SchemaManager.java:27)
    at edu.wpi.disco.rt.DiscoRT.start(DiscoRT.java:118)
    at edu.wpi.always.cm.CollaborationManager.start(CollaborationManager.java:71)
    at edu.wpi.always.Always.start(Always.java:197)
    at edu.wpi.always.Always.main(Always.java:45)

Sent {"msg_type":"gaze","msg_body":{"vertical":"0.0058333334","horizontal":"-0.095625"}}

**Comment by charlesrich** [comment]
Cannot reproduce. Closing
