### ISSUE TITLE
Inconsistent ontology from Weather Plugin

### ISSUE THREAD

**Issue by raggroupkathleen** [always-on/always#235]
When you try to access the weather plugin the system freezes and you get the following error:

Loaded plugin: edu.wpi.always.greetings.GreetingsPlugin@23801b75
Loaded plugin: edu.wpi.always.enroll.EnrollPlugin@21c22eaf
Exception in thread "main" org.semanticweb.owlapi.reasoner.InconsistentOntologyException: Inconsistent ontology
    at com.clarkparsia.pellet.owlapiv3.PelletReasoner.convert(PelletReasoner.java:360)
    at com.clarkparsia.pellet.owlapiv3.PelletReasoner.getDataPropertyValues(PelletReasoner.java:438)
    at edu.wpi.always.user.owl.OntologyIndividual.getDataPropertyValues(OntologyIndividual.java:64)
    at edu.wpi.always.user.owl.OntologyIndividual.getDataPropertyValue(OntologyIndividual.java:72)
    at edu.wpi.always.user.owl.OntologyIndividual.getDataPropertyValue(OntologyIndividual.java:68)
    at edu.wpi.always.user.owl.OntologyUserModel.getProperty(OntologyUserModel.java:67)
    at edu.wpi.always.user.UserModelBase.getCloseness(UserModelBase.java:44)
    at edu.wpi.always.RelationshipManager.getSession(RelationshipManager.java:23)
    at edu.wpi.always.cm.schemas.SessionSchema.<init>(SessionSchema.java:42)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:147)
    at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:348)
    at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:272)
    at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:370)
    at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
    at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:692)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:671)
    at edu.wpi.disco.rt.schema.SchemaManager$ConfigSchemaFactory.create(SchemaManager.java:96)
    at edu.wpi.disco.rt.schema.SchemaManager.start(SchemaManager.java:37)
    at edu.wpi.disco.rt.schema.SchemaManager.startUp(SchemaManager.java:27)
    at edu.wpi.disco.rt.DiscoRT.start(DiscoRT.java:118)
    at edu.wpi.always.cm.CollaborationManager.start(CollaborationManager.java:71)
    at edu.wpi.always.Always.start(Always.java:197)
    at edu.wpi.always.Always.main(Always.java:45)

@charlesrich Any ideas? This is from the latest update. (This note is from Lazlo and I wanted to test the at feature)

**Comment by charlesrich** [comment]
Hi @raggroupkathleen, thank you for using GitHub to post this!  @lring

This is an intermittent problem we have seen before but have not been able to diagnose.  It almost surely has to do with the status of the file always/user/User.owl, which holds the user model.   Have you run the system since this error?  If not, could you please email me (rich@wpi.edu) the current User.owl file.   Or if you can reproduce the error, mail me the file at that time.

In the meanwhile, use Eclipse Replace From > HEAD Version to replace User.owl (it shows up as agent/USER/User.owl in Eclipse) with a fresh copy from the repo, and the problem should go away.  If it does not, then something very funny is going on in your configuration.

Final question, what did you do before you accessed the weather plugin?

**Comment by raggroupkathleen** [comment]
@charlesrich 

I just reran the weather since earlier when it crashed twice and it worked fine. When it crashed both times originally it was right at the start of the interaction when the agent asked if I wanted to hear the weather.

**Comment by charlesrich** [comment]
Ok, looks like another intermittent error got away!   If it happens again, please attach a copy of USER/User.owl
