### ISSUE TITLE
Skype Crash w Reeti

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#351]
Interesting.  The Skype plugin (see SkypeSchema) _does_ turn off the camera if in Unity mode, but does not in Reeti mode, because I thought that using the web cam on the PC should not interfere with Reeti face tracking.  But of course I could not test it.

Could you please take a closer look at the FacePerception.cpp code and see why it should care in Reeti mode whether the web cam is in use (e.g., look at initReetiShoreEngine).  Perhaps there is an unnecessary dependency in the code.

Mohammad, do you have any idea?

Tx, -Chuck

P.S. It is exactly for this kind of testing that we are leaving a Reeti with you at WPI :-)

---------- Forwarded message ----------
From: Behrooz, Morteza mbehrooz@wpi.edu
Date: Tue, May 13, 2014 at 9:46 PM
Subject: Skype and facetracking.
To: "Rich, Charles" rich@wpi.edu

Hi,

Ayesha encountered an interesting bug today that apparently Skype plugin will crash when face tracking is used. It makes sense for it to be caused by both processes (roughly speaking) using camera. I think that the logical solution is obviously to turn off face tracking during the call.

Yours, M

Received {"msg_type":"menu_selected","msg_body":{"text":"Make a Skype call"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Starting UseSkype...
Exception in thread "edu.wpi.always.cm.perceptors.sensor.face.ShoreFacePerceptor$Reeti" java.lang.RuntimeException: java.lang.Error: Invalid memory access
at edu.wpi.cetask.Utils.rethrow(Utils.java:207)
at edu.wpi.disco.rt.util.ThreadPools.afterExecute(ThreadPools.java:124)
at edu.wpi.disco.rt.util.ThreadPools.access$1(ThreadPools.java:91)
at edu.wpi.disco.rt.util.ThreadPools$1.afterExecute(ThreadPools.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Error: Invalid memory access
at com.sun.jna.Native.invokeStructure(Native Method)
at com.sun.jna.Native.invokeStructure(Native.java:1741)
at com.sun.jna.Function.invoke(Function.java:408)
at com.sun.jna.Function.invoke(Function.java:315)
at com.sun.jna.Library$Handler.invoke(Library.java:212)
at com.sun.proxy.$Proxy0.getReetiFaceInfo(Unknown Source)
at edu.wpi.always.cm.perceptors.sensor.face.ShoreFacePerceptor$Reeti.getFaceInfo(ShoreFacePerceptor.java:130)
at edu.wpi.always.cm.perceptors.sensor.face.ShoreFacePerceptor.run(ShoreFacePerceptor.java:51)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask$Sync.innerRunAndReset(Unknown Source)
at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at edu.wpi.disco.rt.util.ThreadPools$ScheduledFutureTask.run(ThreadPools.java:174)
... 3 more

**Comment by mbehrooz** [comment]
Most possibly resolved.
