### ISSUE TITLE
NullPointerException in HealthSchema

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#457]
See 
https://www.dropbox.com/s/tptrdc7kr2almr2/User.2014-11-19_16_25_38.csv?dl=0
https://www.dropbox.com/s/d6jd2h6ejailalu/User.2014-11-19_16_25_38.txt?dl=0
https://www.dropbox.com/s/is9wkx8hvyy1j6q/User.2014-11-19_16_25_38.owl?dl=0

Exception in thread "plugins.HealthSchema" java.lang.NullPointerException

```
at pluginCore.ScriptbuilderCoreScript.<init>(ScriptbuilderCoreScript.java:42)

at pluginCore.AADialogStateTransition.run(RAGDialogueStateTransition.java:18)

at edu.wpi.disco.rt.menu.AdjacencyPairBase.nextState(AdjacencyPairBase.java:65)

at pluginCore.ScriptbuilderCoreScript.nextState(ScriptbuilderCoreScript.java:58)

at edu.wpi.disco.rt.menu.MenuTurnStateMachine.nextState(MenuTurnStateMachine.java:168)

at edu.wpi.disco.rt.menu.MenuTurnStateMachine.build(MenuTurnStateMachine.java:117)

at edu.wpi.disco.rt.schema.SchemaBase.propose(SchemaBase.java:104)

at edu.wpi.always.cm.schemas.ActivityStateMachineSchema.runActivity(ActivityStateMachineSchema.java:27)

at pluginCore.ScriptbuilderSchema.runActivity(ScriptbuilderSchema.java:31)

at edu.wpi.always.cm.schemas.ActivitySchema.run(ActivitySchema.java:38)

at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

at java.util.concurrent.FutureTask.runAndReset(Unknown Source)

at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)

at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)

at edu.wpi.disco.rt.util.ThreadPools$ScheduledFutureTask.run(ThreadPools.java:178)

at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

at java.lang.Thread.run(Unknown Source)
```

**Comment by zessie** [comment]
This has been fixed. Lazlo is working on a new push request at this point.
